export const reinforcerData = [
    { id: 'reinforcer-1', name: '3D painting' },
    { id: 'reinforcer-2', name: 'ABC song (YouTube)' },
    { id: 'reinforcer-3', name: 'ABCYa games on iPad' },
    { id: 'reinforcer-4', name: 'Access to a favorite toy' },
    {
        id: 'reinforcer-5',
        name: 'Access to assistance after appropriate waiting',
    },
    { id: 'reinforcer-6', name: 'Access to markers after completing task' },
    { id: 'reinforcer-7', name: 'Access to musical toys' },
    { id: 'reinforcer-8', name: 'Access to playtime after compliance' },
    { id: 'reinforcer-9', name: 'Access to preferred edible' },
    {
        id: 'reinforcer-10',
        name: 'Access to preferred item after appropriate waiting',
    },
    { id: 'reinforcer-11', name: 'Access to preferred peer activity' },
    { id: 'reinforcer-12', name: 'Access to preferred role (line leader)' },
    { id: 'reinforcer-13', name: 'Access to preferred snack after request' },
    { id: 'reinforcer-14', name: 'Access to preferred toy' },
    { id: 'reinforcer-15', name: 'Access to preferred toy (slime)' },
    { id: 'reinforcer-16', name: 'Access to preferred video (limited time)' },
    { id: 'reinforcer-17', name: 'Access to snack after appropriate request' },
    { id: 'reinforcer-18', name: 'Action figures' },
    { id: 'reinforcer-19', name: 'Activity' },
    { id: 'reinforcer-20', name: 'Ahoy cookies chocolate chips' },
    { id: 'reinforcer-21', name: 'Airplane ride (on adult)' },
    { id: 'reinforcer-22', name: 'Almonds' },
    { id: 'reinforcer-23', name: 'Apple juice' },
    { id: 'reinforcer-24', name: 'Apple slices' },
    { id: 'reinforcer-25', name: 'Art activity' },
    { id: 'reinforcer-26', name: 'Art and craft activity' },
    { id: 'reinforcer-27', name: 'Ask questions during question time' },
    { id: 'reinforcer-28', name: 'Attention' },
    { id: 'reinforcer-29', name: 'Back rub' },
    { id: 'reinforcer-30', name: 'Back scratch' },
    { id: 'reinforcer-31', name: 'Bacon' },
    { id: 'reinforcer-32', name: 'Bake cookies at home' },
    { id: 'reinforcer-33', name: 'Baby carrots' },
    { id: 'reinforcer-34', name: 'Ball drop toys' },
    { id: 'reinforcer-35', name: 'Banana' },
    { id: 'reinforcer-36', name: 'Banana and peanut butter' },
    { id: 'reinforcer-37', name: 'Barbie' },
    { id: 'reinforcer-38', name: 'Barbie doll' },
    { id: 'reinforcer-39', name: "Barbie's house" },
    { id: 'reinforcer-40', name: 'Baseball videos (YouTube)' },
    { id: 'reinforcer-41', name: 'Bean play' },
    { id: 'reinforcer-42', name: 'Beanbag' },
    { id: 'reinforcer-43', name: 'Beads' },
    { id: 'reinforcer-44', name: 'Being the teacher' },
    { id: 'reinforcer-45', name: 'Bin of dry beans and rice' },
    { id: 'reinforcer-46', name: 'Blankets' },
    { id: 'reinforcer-47', name: 'Blankets over head' },
    { id: 'reinforcer-48', name: 'Blocks' },
    { id: 'reinforcer-49', name: 'Blowing bubbles' },
    { id: 'reinforcer-50', name: 'Blueberries' },
    { id: 'reinforcer-51', name: 'Body pillow' },
    { id: 'reinforcer-52', name: 'Body sock' },
    { id: 'reinforcer-53', name: 'Books' },
    { id: 'reinforcer-54', name: 'Books that make sounds' },
    { id: 'reinforcer-55', name: 'Bouncing on an exercise ball' },
    { id: 'reinforcer-56', name: 'Box of things that smell good' },
    { id: 'reinforcer-57', name: 'Box with assorted dry pasta' },
    { id: 'reinforcer-58', name: 'Break time' },
    { id: 'reinforcer-59', name: 'Breaks' },
    { id: 'reinforcer-60', name: 'Brouwnies (Brownies)' },
    { id: 'reinforcer-61', name: 'Bubbles - chase, blow in fan' },
    { id: 'reinforcer-62', name: 'Build with play doh' },
    { id: 'reinforcer-63', name: 'Busy boards' },
    { id: 'reinforcer-64', name: 'Candy' },
    { id: 'reinforcer-65', name: 'Candy Land' },
    { id: 'reinforcer-66', name: 'Cards' },
    { id: 'reinforcer-67', name: 'Cars' },
    { id: 'reinforcer-68', name: 'Cereals' },
    { id: 'reinforcer-69', name: 'Cheese stick' },
    { id: 'reinforcer-70', name: 'Cheerios' },
    { id: 'reinforcer-71', name: 'Cheering' },
    { id: 'reinforcer-72', name: 'Cheeto' },
    { id: 'reinforcer-73', name: 'Chew toys' },
    { id: 'reinforcer-74', name: 'Chicken' },
    { id: 'reinforcer-75', name: 'Chicken nuggets' },
    { id: 'reinforcer-76', name: 'Chicken quesadilla' },
    { id: 'reinforcer-77', name: 'Chicken sandwich' },
    { id: 'reinforcer-78', name: 'Chicken tenders' },
    { id: 'reinforcer-79', name: 'Chips' },
    { id: 'reinforcer-80', name: 'Chips Ahoy cookies' },
    { id: 'reinforcer-81', name: 'Chips and ranch dip' },
    {
        id: 'reinforcer-82',
        name: 'Choice between two games after task completion',
    },
    { id: 'reinforcer-83', name: 'Choice of break activity' },
    { id: 'reinforcer-84', name: 'Choice of next activity' },
    { id: 'reinforcer-85', name: 'Choice time' },
    { id: 'reinforcer-86', name: 'Chocolate' },
    { id: 'reinforcer-87', name: 'Chocolate brownie' },
    { id: 'reinforcer-88', name: 'Chocolate caramel M&Ms' },
    { id: 'reinforcer-89', name: 'Chocolate candies' },
    { id: 'reinforcer-90', name: 'Chocolate cookies' },
    { id: 'reinforcer-91', name: 'Churros' },
    { id: 'reinforcer-92', name: 'Clapping' },
    { id: 'reinforcer-93', name: 'Clapping hands' },
    { id: 'reinforcer-94', name: 'Class iPad' },
    { id: 'reinforcer-95', name: 'Climbing' },
    { id: 'reinforcer-96', name: 'Climbing through a tunnel or ball pit' },
    { id: 'reinforcer-97', name: 'Coloring' },
    { id: 'reinforcer-98', name: 'Coloring a picture on the computer or iPad' },
    { id: 'reinforcer-99', name: 'Comics' },
    { id: 'reinforcer-100', name: 'Connect 4' },
    { id: 'reinforcer-101', name: 'Connect 4 game' },
    { id: 'reinforcer-102', name: 'Conversation with RBT' },
    { id: 'reinforcer-103', name: 'Conversate about geography' },
    { id: 'reinforcer-104', name: 'Cookies' },
    { id: 'reinforcer-105', name: 'Costume' },
    { id: 'reinforcer-106', name: 'Crackers' },
    { id: 'reinforcer-107', name: 'Create a bracelet' },
    {
        id: 'reinforcer-108',
        name: 'Create/Design a logo or draw company logos',
    },
    { id: 'reinforcer-109', name: 'Creating a creative project at Canva app' },
    { id: 'reinforcer-110', name: 'Cupcake' },
    { id: 'reinforcer-111', name: 'Cupcakes' },
    { id: 'reinforcer-112', name: 'Dancing' },
    { id: 'reinforcer-113', name: 'Decorating cookies' },
    { id: 'reinforcer-114', name: 'Deep pressure' },
    { id: 'reinforcer-115', name: 'Delivering something to another room' },
    { id: 'reinforcer-116', name: 'Descriptive praises' },
    { id: 'reinforcer-117', name: 'Diamond painting' },
    { id: 'reinforcer-118', name: 'Diary of a wimpy kid book' },
    { id: 'reinforcer-119', name: 'Dinosaur' },
    { id: 'reinforcer-120', name: 'Dinosaurs' },
    { id: 'reinforcer-121', name: 'Disney stickers' },
    { id: 'reinforcer-122', name: 'do hair style' },
    { id: 'reinforcer-123', name: 'Doing a puzzle on the iPad' },
    { id: 'reinforcer-124', name: 'Dolls' },
    { id: 'reinforcer-125', name: 'Dominoes' },
    { id: 'reinforcer-126', name: 'Donuts' },
    { id: 'reinforcer-127', name: 'Doritos chips' },
    { id: 'reinforcer-128', name: 'Double portion of food during meal' },
    { id: 'reinforcer-129', name: 'Draw on iPad with Apple Pencil' },
    { id: 'reinforcer-130', name: 'Draw on sensory board' },
    { id: 'reinforcer-131', name: 'Drawing' },
    { id: 'reinforcer-132', name: 'Drawing favorite characters' },
    { id: 'reinforcer-133', name: 'Dress up play' },
    { id: 'reinforcer-134', name: 'Drink of water' },
    { id: 'reinforcer-135', name: 'Drop lowest grade once per quarter' },
    { id: 'reinforcer-136', name: 'Drum toy' },
    { id: 'reinforcer-137', name: 'Earn money for rewards' },
    { id: 'reinforcer-138', name: 'Edible' },
    { id: 'reinforcer-139', name: 'Edible (apple juice)' },
    { id: 'reinforcer-140', name: 'Edible (popcorn)' },
    { id: 'reinforcer-141', name: 'Edibles' },
    { id: 'reinforcer-142', name: 'Edibles (snack)' },
    { id: 'reinforcer-143', name: 'Eggs' },
    { id: 'reinforcer-144', name: 'Exercise ball' },
    { id: 'reinforcer-145', name: 'Exercise break' },
    { id: 'reinforcer-146', name: 'Extra computer or screen time' },
    { id: 'reinforcer-147', name: 'Extra credit' },
    { id: 'reinforcer-148', name: 'Extra time on a favorite activity' },
    { id: 'reinforcer-149', name: 'Extra time with a favorite toy' },
    { id: 'reinforcer-150', name: 'Facial expression' },
    { id: 'reinforcer-151', name: 'Farm toys' },
    { id: 'reinforcer-152', name: 'Favorite sushi' },
    { id: 'reinforcer-153', name: 'Fidget toys' },
    { id: 'reinforcer-154', name: 'Field trips' },
    { id: 'reinforcer-155', name: 'Fine motor pen magnets board' },
    { id: 'reinforcer-156', name: 'Finger painting' },
    { id: 'reinforcer-157', name: "Five Nights at Freddy's toys" },
    { id: 'reinforcer-158', name: 'Five minutes conversation with RBT' },
    { id: 'reinforcer-159', name: 'Free play' },
    { id: 'reinforcer-160', name: 'Free play for 2 minutes' },
    { id: 'reinforcer-161', name: 'Free play with kinetic sand' },
    { id: 'reinforcer-162', name: 'Free time' },
    { id: 'reinforcer-163', name: 'Fried chicken' },
    { id: 'reinforcer-164', name: 'Friday cartoon video' },
    { id: 'reinforcer-165', name: 'Fruit' },
    { id: 'reinforcer-166', name: 'Fruit gummies/snacks' },
    { id: 'reinforcer-167', name: 'Game on the TV' },
    { id: 'reinforcer-168', name: 'Gear toys' },
    { id: 'reinforcer-169', name: 'Gift card reward' },
    { id: 'reinforcer-170', name: 'Give a high five' },
    { id: 'reinforcer-171', name: 'Give me 5' },
    { id: 'reinforcer-172', name: 'Give me five' },
    { id: 'reinforcer-173', name: 'Give me those 10' },
    { id: 'reinforcer-174', name: 'Giving squeezes on the hand or arm' },
    { id: 'reinforcer-175', name: 'Go out to play with his friend' },
    { id: 'reinforcer-176', name: "Go to counselor's office" },
    { id: 'reinforcer-177', name: 'Go to park' },
    { id: 'reinforcer-178', name: 'Go to the park' },
    { id: 'reinforcer-179', name: 'Going in a tent' },
    { id: 'reinforcer-180', name: 'Going to the park' },
    { id: 'reinforcer-181', name: 'Going to the playground' },
    { id: 'reinforcer-182', name: 'Going to the school book fair' },
    { id: 'reinforcer-183', name: 'Good job' },
    { id: 'reinforcer-184', name: 'Granola Bars pieces' },
    { id: 'reinforcer-185', name: 'Grapes' },
    { id: 'reinforcer-186', name: 'Guess Who (board game)' },
    { id: 'reinforcer-187', name: 'Gummies' },
    { id: 'reinforcer-188', name: 'Gummy bears' },
    { id: 'reinforcer-189', name: 'Gummy snacks' },
    { id: 'reinforcer-190', name: 'Hand shake' },
    { id: 'reinforcer-191', name: 'Head, shoulders, knees and toes song' },
    { id: 'reinforcer-192', name: 'Healthy snack' },
    { id: 'reinforcer-193', name: 'Healthy snacks' },
    { id: 'reinforcer-194', name: 'Hershey Kisses' },
    { id: 'reinforcer-195', name: 'Hi 5' },
    { id: 'reinforcer-196', name: 'High five' },
    { id: 'reinforcer-197', name: 'High fives' },
    { id: 'reinforcer-198', name: 'Homeward pass' },
    { id: 'reinforcer-199', name: 'Honeybun' },
    { id: 'reinforcer-200', name: 'Horsey - ride (on adult)' },
    { id: 'reinforcer-201', name: 'Hot Dog' },
    { id: 'reinforcer-202', name: 'Hug' },
    { id: 'reinforcer-203', name: 'Hugs' },
    { id: 'reinforcer-204', name: 'Ice cream' },
    { id: 'reinforcer-205', name: 'Ice pop' },
    { id: 'reinforcer-206', name: 'Jalapeño Cheetos' },
    { id: 'reinforcer-207', name: 'Jellybean' },
    { id: 'reinforcer-208', name: 'Juice' },
    { id: 'reinforcer-209', name: 'Jump on trampoline' },
    { id: 'reinforcer-210', name: 'Jumping' },
    { id: 'reinforcer-211', name: 'Jumping on a trampoline' },
    { id: 'reinforcer-212', name: 'Kerplunk game' },
    { id: 'reinforcer-213', name: 'Kicking a ball into a soccer net' },
    { id: 'reinforcer-214', name: 'Kinetic sand' },
    { id: 'reinforcer-215', name: 'Kissess (Kisses)' },
    { id: 'reinforcer-216', name: 'Laughing/giggling' },
    { id: 'reinforcer-217', name: 'LEAVE CLASS 5 min early for lunch' },
    { id: 'reinforcer-218', name: 'Legos' },
    { id: 'reinforcer-219', name: 'Legos (only adult around him)' },
    { id: 'reinforcer-220', name: 'Lion lots' },
    { id: 'reinforcer-221', name: 'Listen to iPod' },
    { id: 'reinforcer-222', name: 'Listen to music' },
    { id: 'reinforcer-223', name: 'Listen to music on iPad' },
    { id: 'reinforcer-224', name: 'Listen to story on CD' },
    { id: 'reinforcer-225', name: 'Listening to music' },
    { id: 'reinforcer-226', name: 'Little people set' },
    { id: 'reinforcer-227', name: 'LOL toys' },
    { id: 'reinforcer-228', name: 'Lollipop' },
    { id: 'reinforcer-229', name: 'Looking out the window' },
    { id: 'reinforcer-230', name: 'Lotion rub' },
    { id: 'reinforcer-231', name: 'Lunch bunch with teacher' },
    { id: 'reinforcer-232', name: 'Lunch/snack helper' },
    { id: 'reinforcer-233', name: 'M&Ms' },
    { id: 'reinforcer-234', name: 'Magazines' },
    { id: 'reinforcer-235', name: 'Magna tiles' },
    { id: 'reinforcer-236', name: 'Magna tiles' },
    { id: 'reinforcer-237', name: 'Magnet tracing Pad' },
    { id: 'reinforcer-238', name: 'Magnetic Drawing Board' },
    {
        id: 'reinforcer-239',
        name: 'Make a collage or drawing for someone of choice',
    },
    { id: 'reinforcer-240', name: 'Make Origami' },
    { id: 'reinforcer-241', name: 'Make slime' },
    { id: 'reinforcer-242', name: 'Making a berry milkshake' },
    { id: 'reinforcer-243', name: 'Making funny faces' },
    { id: 'reinforcer-244', name: 'Making pancakes' },
    { id: 'reinforcer-245', name: 'Mancala' },
    { id: 'reinforcer-246', name: 'Manicure' },
    { id: 'reinforcer-247', name: 'Marble maze' },
    { id: 'reinforcer-248', name: 'Marbles' },
    { id: 'reinforcer-249', name: 'Mario toys' },
    { id: 'reinforcer-250', name: 'Marshmallow' },
    { id: 'reinforcer-251', name: 'Matching shapes egg set' },
    { id: 'reinforcer-252', name: 'Mcdonalds gift card' },
    { id: 'reinforcer-253', name: "McDonald's" },
    { id: 'reinforcer-254', name: 'Mini Marshmallows' },
    { id: 'reinforcer-255', name: 'Mirrors' },
    { id: 'reinforcer-256', name: 'Money for vending machine' },
    { id: 'reinforcer-257', name: 'Mozarella sticks' },
    { id: 'reinforcer-258', name: 'Ms. Potato' },
    { id: 'reinforcer-259', name: 'Multimedia room' },
    { id: 'reinforcer-260', name: 'Musical toys' },
    { id: 'reinforcer-261', name: 'Nintendo DS' },
    { id: 'reinforcer-262', name: 'Non Edible' },
    { id: 'reinforcer-263', name: 'Non-Edibles' },
    { id: 'reinforcer-264', name: 'Nutella Cookies' },
    { id: 'reinforcer-265', name: 'Nuts' },
    { id: 'reinforcer-266', name: 'One-on-one time With adult' },
    { id: 'reinforcer-267', name: 'Oreo cookies' },
    { id: 'reinforcer-268', name: 'Others' },
    { id: 'reinforcer-269', name: 'Outside walk' },
    { id: 'reinforcer-270', name: 'Painting' },
    { id: 'reinforcer-271', name: 'Painting by number colors' },
    { id: 'reinforcer-272', name: 'Peer play' },
    { id: 'reinforcer-273', name: 'Peer Play' },
    { id: 'reinforcer-274', name: 'Peppermint candy' },
    { id: 'reinforcer-275', name: 'Peppa Pig Toy' },
    { id: 'reinforcer-276', name: 'Pepperoni' },
    { id: 'reinforcer-277', name: 'Percent' },
    { id: 'reinforcer-278', name: 'Pieces of Cookies' },
    { id: 'reinforcer-279', name: 'Pick ups' },
    { id: 'reinforcer-280', name: 'Piggy - back ride (on adult)' },
    { id: 'reinforcer-281', name: 'Piggyback rides' },
    { id: 'reinforcer-282', name: 'Pizza' },
    { id: 'reinforcer-283', name: 'Play ABCYa games on iPad' },
    { id: 'reinforcer-284', name: 'Play basketball' },
    { id: 'reinforcer-285', name: 'Play Basketball Together' },
    { id: 'reinforcer-286', name: 'Play board games' },
    { id: 'reinforcer-287', name: 'Play doh' },
    { id: 'reinforcer-288', name: 'Play doh (only with adult around him)' },
    { id: 'reinforcer-289', name: 'Play games tablet' },
    { id: 'reinforcer-290', name: 'Play in the gameroom' },
    { id: 'reinforcer-291', name: 'Play instructional games on ABCYa' },
    {
        id: 'reinforcer-292',
        name: 'Play instruments such as guitar or piano for the RBT or family members',
    },
    { id: 'reinforcer-293', name: 'Play Mancala' },
    { id: 'reinforcer-294', name: 'Play minecraft with friends' },
    { id: 'reinforcer-295', name: 'Play mini hockey' },
    { id: 'reinforcer-296', name: 'Play musical chairs' },
    { id: 'reinforcer-297', name: 'Play on iPad' },
    { id: 'reinforcer-298', name: 'Play on Pacman machine' },
    { id: 'reinforcer-299', name: 'Play on PS5' },
    { id: 'reinforcer-300', name: 'Play on PS5 for maximum 45 minutes' },
    { id: 'reinforcer-301', name: 'Play outside' },
    { id: 'reinforcer-302', name: 'Play piano for an audience' },
    { id: 'reinforcer-303', name: 'Play simon says with the RBT' },
    { id: 'reinforcer-304', name: 'Play Soccer Ball at Playground Time' },
    { id: 'reinforcer-305', name: 'Play soccer' },
    { id: 'reinforcer-306', name: 'Play table games' },
    { id: 'reinforcer-307', name: 'Play tap game' },
    { id: 'reinforcer-308', name: 'Play tic-tac-toe with the RBT' },
    { id: 'reinforcer-309', name: 'Play UNO' },
    { id: 'reinforcer-310', name: 'Play video games with friends' },
    { id: 'reinforcer-311', name: 'Play with balloon' },
    {
        id: 'reinforcer-312',
        name: 'Play with choice of reinforcers from RBTs box',
    },
    { id: 'reinforcer-313', name: 'Play with dinosaurs' },
    { id: 'reinforcer-314', name: 'Play with fidget toys' },
    { id: 'reinforcer-315', name: 'Play with friend' },
    { id: 'reinforcer-316', name: 'Play with friend Jason' },
    { id: 'reinforcer-317', name: 'Play with friend Lia' },
    { id: 'reinforcer-318', name: 'Play with his favorite Toys' },
    { id: 'reinforcer-319', name: 'Play with his pet dog' },
    { id: 'reinforcer-320', name: 'Play with kinetic sand' },
    { id: 'reinforcer-321', name: 'Play with legos' },
    { id: 'reinforcer-322', name: 'Play with legos together' },
    { id: 'reinforcer-323', name: 'Play with magformers' },
    { id: 'reinforcer-324', name: 'Play with magnets' },
    { id: 'reinforcer-325', name: 'Play with magnetic drawing board' },
    { id: 'reinforcer-326', name: 'Play with matching shapes egg set' },
    { id: 'reinforcer-327', name: 'Play with new toys' },
    { id: 'reinforcer-328', name: 'Play with other friends in class' },
    { id: 'reinforcer-329', name: 'Play with peer' },
    { id: 'reinforcer-330', name: 'Play with play-doh' },
    { id: 'reinforcer-331', name: 'Play with preferred toy from sensory box' },
    { id: 'reinforcer-332', name: 'Play with sensory/fidget toys' },
    { id: 'reinforcer-333', name: 'Play with shaving cream on a cookie sheet' },
    { id: 'reinforcer-334', name: 'Play with slime' },
    { id: 'reinforcer-335', name: 'Play with squishy ball' },
    { id: 'reinforcer-336', name: 'Play with Super Mario toys' },
    { id: 'reinforcer-337', name: 'Play with toy from sensory box' },
    {
        id: 'reinforcer-338',
        name: 'Play with Wooden Shape Puzzle Pattern Blocks',
    },
    { id: 'reinforcer-339', name: 'Play with your cat' },
    { id: 'reinforcer-340', name: 'Play-doh' },
    { id: 'reinforcer-341', name: 'Playing a game of chase' },
    { id: 'reinforcer-342', name: 'Playing a game on an iPad' },
    { id: 'reinforcer-343', name: 'Playing a game together' },
    {
        id: 'reinforcer-344',
        name: 'Playing a video game on a console or Gameboy',
    },
    { id: 'reinforcer-345', name: 'Playing basketball' },
    { id: 'reinforcer-346', name: 'Playing board games' },
    { id: 'reinforcer-347', name: 'Playing game on the TV' },
    { id: 'reinforcer-348', name: 'Playing game on the TV' },
    { id: 'reinforcer-349', name: 'Playing in electronic device' },
    { id: 'reinforcer-350', name: 'Playing in iPad' },
    { id: 'reinforcer-351', name: 'Playing in Tablet' },
    { id: 'reinforcer-352', name: 'Playing Letter Soup' },
    { id: 'reinforcer-353', name: 'Playing Mini Hockey' },
    { id: 'reinforcer-354', name: 'Playing online games in computer' },
    { id: 'reinforcer-355', name: 'Playing Tag with peers' },
    { id: 'reinforcer-356', name: 'Playing UNO cards game' },
    { id: 'reinforcer-357', name: 'Playing with car toys' },
    { id: 'reinforcer-358', name: 'Playing with Five Nights at Freddy' },
    { id: 'reinforcer-359', name: 'Playing with play-doh' },
    {
        id: 'reinforcer-360',
        name: 'Playing with shaving cream on a cookie sheet',
    },
    { id: 'reinforcer-361', name: 'Playing with slime' },
    { id: 'reinforcer-362', name: 'Playing with toy animals' },
    { id: 'reinforcer-363', name: 'Pop up toys' },
    { id: 'reinforcer-364', name: 'Popcorn' },
    { id: 'reinforcer-365', name: 'Potato chips' },
    { id: 'reinforcer-366', name: 'Praise (Great job!, You did it!, etc.)' },
    { id: 'reinforcer-367', name: 'Predictable play patterns' },
    { id: 'reinforcer-368', name: 'Preferred Toy Car' },
    { id: 'reinforcer-369', name: 'Preferred toys' },
    { id: 'reinforcer-370', name: 'Pretending play' },
    { id: 'reinforcer-371', name: 'Prize from treasure box' },
    { id: 'reinforcer-372', name: 'Prize from treasure box' },
    { id: 'reinforcer-373', name: 'Protein bars' },
    { id: 'reinforcer-374', name: 'Pringles' },
    { id: 'reinforcer-375', name: 'Pringles chips' },
    { id: 'reinforcer-376', name: 'Puppet play' },
    { id: 'reinforcer-377', name: 'Puzzles' },
    { id: 'reinforcer-378', name: 'Raisins' },
    { id: 'reinforcer-379', name: 'Raising Eyebrows' },
    { id: 'reinforcer-380', name: 'Read a book' },
    { id: 'reinforcer-381', name: 'Read out loud' },
    { id: 'reinforcer-382', name: 'Reading a story' },
    { id: 'reinforcer-383', name: 'Relaxing tickles' },
    { id: 'reinforcer-384', name: 'Research on special interest on Google' },
    { id: 'reinforcer-385', name: 'Rest' },
    { id: 'reinforcer-386', name: 'Ribbon' },
    { id: 'reinforcer-387', name: 'Rice play' },
    { id: 'reinforcer-388', name: 'Ride bicycle' },
    { id: 'reinforcer-389', name: 'Ride Bicycle' },
    { id: 'reinforcer-390', name: 'Ride in-cars' },
    { id: 'reinforcer-391', name: 'Ride scooter' },
    { id: 'reinforcer-392', name: 'Riding an elevator' },
    { id: 'reinforcer-393', name: 'Riding bicycle' },
    { id: 'reinforcer-394', name: 'Ringpop' },
    { id: 'reinforcer-395', name: 'Robots' },
    { id: 'reinforcer-396', name: 'Rocking' },
    { id: 'reinforcer-397', name: 'Rubbing noses with the RBT' },
    { id: 'reinforcer-398', name: 'Ruffles chips' },
    { id: 'reinforcer-399', name: 'Run outside' },
    { id: 'reinforcer-400', name: 'Running in the hallway' },
    { id: 'reinforcer-401', name: 'Sand table' },
    { id: 'reinforcer-402', name: 'School store Access' },
    { id: 'reinforcer-403', name: 'Scents/perfumes' },
    { id: 'reinforcer-404', name: 'Sea animals puzzle' },
    { id: 'reinforcer-405', name: 'Sea animals toy' },
    { id: 'reinforcer-406', name: 'Sensory' },
    { id: 'reinforcer-407', name: 'Sensory bottles' },
    { id: 'reinforcer-408', name: 'Sensory foam' },
    { id: 'reinforcer-409', name: 'Sequin pillows' },
    { id: 'reinforcer-410', name: 'Shaking head' },
    { id: 'reinforcer-411', name: 'Shaking Head' },
    { id: 'reinforcer-412', name: 'Shaving cream play' },
    { id: 'reinforcer-413', name: 'Shredding paper' },
    { id: 'reinforcer-414', name: 'Short breaks' },
    { id: 'reinforcer-415', name: 'Short iPad time' },
    { id: 'reinforcer-416', name: 'Silly putty or TheraPutty' },
    { id: 'reinforcer-417', name: 'Singing' },
    { id: 'reinforcer-418', name: 'Singing a nursery rhyme together' },
    { id: 'reinforcer-419', name: 'Singing along mother goose songs' },
    { id: 'reinforcer-420', name: 'Skate' },
    { id: 'reinforcer-421', name: 'Skittles' },
    { id: 'reinforcer-422', name: 'Slime' },
    { id: 'reinforcer-423', name: 'Slingshot rockets' },
    { id: 'reinforcer-424', name: 'Slinky' },
    { id: 'reinforcer-425', name: 'Small amount of' },
    { id: 'reinforcer-426', name: 'Small Pizza Slice' },
    { id: 'reinforcer-427', name: 'Small soldiers' },
    { id: 'reinforcer-428', name: 'Smart Brain Quest' },
    { id: 'reinforcer-429', name: 'Smiling' },
    { id: 'reinforcer-430', name: 'Snow cone at school' },
    { id: 'reinforcer-431', name: 'Social' },
    { id: 'reinforcer-432', name: 'Social (give me five)' },
    { id: 'reinforcer-433', name: 'Social (verbal reinforcement)' },
    {
        id: 'reinforcer-434',
        name: 'Social praise (Thank you for using your words!)',
    },
    { id: 'reinforcer-435', name: 'Social Price' },
    { id: 'reinforcer-436', name: 'Social Reinforcers good job' },
    { id: 'reinforcer-437', name: 'Sounds (produced by adult)' },
    { id: 'reinforcer-438', name: 'Sour Patch Kids' },
    { id: 'reinforcer-439', name: 'Sour patch gummies' },
    { id: 'reinforcer-440', name: 'Spending time with family member' },
    { id: 'reinforcer-441', name: 'Spin toy' },
    { id: 'reinforcer-442', name: 'Spinning toys' },
    { id: 'reinforcer-443', name: 'Spray bottle' },
    { id: 'reinforcer-444', name: 'Squeezes' },
    { id: 'reinforcer-445', name: 'Squeezy bottle tag/play' },
    { id: 'reinforcer-446', name: 'Squirt bottle tag/play' },
    { id: 'reinforcer-447', name: 'Starbucks treat' },
    { id: 'reinforcer-448', name: 'Stay seated within his class group' },
    { id: 'reinforcer-449', name: 'Sticker paint' },
    { id: 'reinforcer-450', name: 'Stickers' },
    { id: 'reinforcer-451', name: 'Stim time' },
    { id: 'reinforcer-452', name: 'Story' },
    { id: 'reinforcer-453', name: 'Strawberry' },
    { id: 'reinforcer-454', name: 'Strawberry fruit' },
    { id: 'reinforcer-455', name: 'Strawberry shake' },
    { id: 'reinforcer-456', name: 'Stress balls' },
    { id: 'reinforcer-457', name: 'Stretchy noodle bands' },
    { id: 'reinforcer-458', name: 'String' },
    { id: 'reinforcer-459', name: 'String Cheese' },
    { id: 'reinforcer-460', name: 'Student leader' },
    { id: 'reinforcer-461', name: 'Stuffed animals' },
    { id: 'reinforcer-462', name: 'Sugar free gummies' },
    { id: 'reinforcer-463', name: 'Sweet snacks' },
    { id: 'reinforcer-464', name: 'Swing in the playground' },
    { id: 'reinforcer-465', name: 'Tablet' },
    { id: 'reinforcer-466', name: 'Takis' },
    { id: 'reinforcer-467', name: 'Talk on phone' },
    { id: 'reinforcer-468', name: 'Talk on the phone' },
    { id: 'reinforcer-469', name: 'Talking about a preferred topic' },
    {
        id: 'reinforcer-470',
        name: 'Talking to or visiting a preferred adult or child',
    },
    { id: 'reinforcer-471', name: 'Tangible' },
    { id: 'reinforcer-472', name: 'Tangibles' },
    { id: 'reinforcer-473', name: 'Teeter Popper toy' },
    { id: 'reinforcer-474', name: 'Tell class a joke' },
    { id: 'reinforcer-475', name: 'Telling a joke' },
    { id: 'reinforcer-476', name: "That's awesome" },
    { id: 'reinforcer-477', name: 'Thomas the Train' },
    { id: 'reinforcer-478', name: 'Thumb up' },
    { id: 'reinforcer-479', name: 'Thumbs up' },
    { id: 'reinforcer-480', name: 'Tickles' },
    { id: 'reinforcer-481', name: 'Tickets for prize drawing' },
    { id: 'reinforcer-482', name: 'Toca boca' },
    { id: 'reinforcer-483', name: 'Token economy' },
    { id: 'reinforcer-484', name: 'Token economy for Guitar Club Mondays' },
    {
        id: 'reinforcer-485',
        name: 'Token economy for judo classes on Mondays, Wednesdays and Fridays',
    },
    { id: 'reinforcer-486', name: 'Toddler Bike' },
    { id: 'reinforcer-487', name: 'Toy animals' },
    { id: 'reinforcer-488', name: 'Toy Cars' },
    { id: 'reinforcer-489', name: 'Toy cars' },
    { id: 'reinforcer-490', name: 'Toy drum' },
    { id: 'reinforcer-491', name: 'Toy piano' },
    { id: 'reinforcer-492', name: 'Toys animals, people, food (plastic)' },
    { id: 'reinforcer-493', name: 'Trampoline' },
    { id: 'reinforcer-494', name: 'Trains' },
    { id: 'reinforcer-495', name: 'Trip to chuck e cheeses' },
    { id: 'reinforcer-496', name: 'Trolls Toys' },
    { id: 'reinforcer-497', name: 'Tumble Tower Game' },
    { id: 'reinforcer-498', name: 'Turn lights on/off' },
    { id: 'reinforcer-499', name: 'Turning lights on/off' },
    { id: 'reinforcer-500', name: 'Twirl in air' },
    { id: 'reinforcer-501', name: 'Twirl on spinning chair' },
    { id: 'reinforcer-502', name: 'UNO cards game' },
    {
        id: 'reinforcer-503',
        name: 'Upon completion, he received social praise and a three-minute break for free play',
    },
    {
        id: 'reinforcer-504',
        name: 'Using Snapchat filters to take pictures/video',
    },
    { id: 'reinforcer-505', name: 'Veggie Straws chips' },
    { id: 'reinforcer-506', name: 'Vegetables' },
    { id: 'reinforcer-507', name: 'Verbal' },
    { id: 'reinforcer-508', name: 'Verbal praise' },
    { id: 'reinforcer-509', name: 'Verbal Praise' },
    { id: 'reinforcer-510', name: 'Verbal praise ("Nice job staying calm!")' },
    {
        id: 'reinforcer-511',
        name: 'Verbal praise ("Nice job staying calm!", "Great asking!")',
    },
    {
        id: 'reinforcer-512',
        name: 'Verbal praise ("Nice job!", "I like how you asked!")',
    },
    {
        id: 'reinforcer-513',
        name: 'Verbal praise (Good job!, You did it!, etc.)',
    },
    { id: 'reinforcer-514', name: 'Verbal praise (You asked so nicely!)' },
    { id: 'reinforcer-515', name: 'Verbal praise and stickers' },
    { id: 'reinforcer-516', name: 'Verbal reinforcement' },
    { id: 'reinforcer-517', name: 'Video' },
    { id: 'reinforcer-518', name: 'Video Games' },
    { id: 'reinforcer-519', name: 'Visual schedule/Task Check List' },
    { id: 'reinforcer-520', name: 'Visit a preferred room' },
    { id: 'reinforcer-521', name: 'Walking outside' },
    { id: 'reinforcer-522', name: 'Warm up and perform jiujitsu activities' },
    { id: 'reinforcer-523', name: 'Watch a movie' },
    { id: 'reinforcer-524', name: 'Watch a preferred video together' },
    { id: 'reinforcer-525', name: 'Watch a video on YouTube' },
    {
        id: 'reinforcer-526',
        name: 'Watch a videos from YouTube about USA presidents',
    },
    { id: 'reinforcer-527', name: 'Watch Tablet' },
    { id: 'reinforcer-528', name: 'Watch TV' },
    { id: 'reinforcer-529', name: 'Watch videos about USA maps' },
    { id: 'reinforcer-530', name: 'Watching a preferred video together' },
    { id: 'reinforcer-531', name: 'Watching jiujitsu videos on YouTube' },
    { id: 'reinforcer-532', name: 'Watching videos about USA maps' },
    { id: 'reinforcer-533', name: 'Watching videos of animals' },
    { id: 'reinforcer-534', name: 'Watching YouTube videos' },
    { id: 'reinforcer-535', name: 'Watering plants at home' },
    { id: 'reinforcer-536', name: 'Water beads' },
    { id: 'reinforcer-537', name: 'Water play' },
    { id: 'reinforcer-538', name: 'Weighted blanket' },
    { id: 'reinforcer-539', name: 'Whistling' },
    { id: 'reinforcer-540', name: 'Winking' },
    { id: 'reinforcer-541', name: 'Wooden train set' },
    { id: 'reinforcer-542', name: 'Working on a puzzle' },
    { id: 'reinforcer-543', name: 'Working on building robots' },
    { id: 'reinforcer-544', name: 'WOW you are smart!' },
    { id: 'reinforcer-545', name: 'Wrinkling nose' },
    { id: 'reinforcer-546', name: 'Yogurt' },
];
